In [1]:
# Import required libraries
import pandas as pd

In [2]:
# Read all the required files
data_path = "../input/infocepts-data-engineering-hiring-hackathon/InfoCept Participants Data/infocept_xml_data_.xml"
out_path = "../input/infocepts-data-engineering-hiring-hackathon/InfoCept Participants Data/infocept_submission.csv"
data_df = pd.read_xml(data_path)
out_df = pd.read_csv(out_path)

In [3]:
# Check the dataframe info
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 24 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   index                     500000 non-null  int64
 1   user_session              500000 non-null  object
 2   total_clicks              500000 non-null  int64
 3   total_items               500000 non-null  int64
 4   total_cats                500000 non-null  int64
 5   max_dwell                 500000 non-null  float64
 6   mean_dwell                500000 non-null  float64
 7   total_duration            500000 non-null  float64
 8   click_rate                500000 non-null  float64
 9   day_of_week               500000 non-null  int64
 10  is_weekend                500000 non-null  int64
 11  is_special_day            500000 non-null  int64
 12  time_of_day               500000 non-null  int64
 13  cat_most_viewed_n_times   500000 non-null  float64
 14  cat_most_viewed           500000 non-null  int64
 15  prod_most_viewed_n_times  500000 non-null  float64
 16  prod_most_viewed          500000 non-null  int64
 17  cat_views_freqs           500000 non-null  float64
 18  prod_views_freqs          500000 non-null  float64
 19  cat_buys_freqs            500000 non-null  float64
 20  prod_buys_freqs           500000 non-null  float64
 21  is_purchase               500000 non-null  int64
 22  start_time_ts             500000 non-null  object
 23  end_time_ts               500000 non-null  object
dtypes: float64(10), int64(11), object(3)
memory usage: 91.6+ MB

1. There are no nulls present in the data. 
2. Here, index is included as one of the columns. However, it's not required in this use case. Hence, let's set the index using 'index' column.
3. Based on the business understanding of columns,

In [5]:
# Remove index column from the dataframe
data_df = data_df.set_index('index')
# Set index name to 'None'
data_df.index.names = [None]

In [10]:
# Display some rows from the dataframe
data_df.head(10)

,user_session,total_clicks,total_items,total_cats,max_dwell,mean_dwell,total_duration,click_rate,day_of_week,is_weekend,...,cat_most_viewed,prod_most_viewed_n_times,prod_most_viewed,cat_views_freqs,prod_views_freqs,cat_buys_freqs,prod_buys_freqs,is_purchase,start_time_ts,end_time_ts
0,8b69208e-7c64-422d-b670-5b9d82d25606,7,2,1,0.511508,5.995878,166.711175,0.072524,1,0,...,2053013560982667520,1.0,1030297,0.267802,0.000945,2.337402e-01,0.000690,0,"October 07, 2019 Monday, 00:08:28","October 26, 2019 Saturday, 16:08:29"
1,8068596c-a2b8-46ca-8791-e10d70520a1f,7,2,1,7.626576,3.529165,0.434185,0.204248,0,0,...,2053013602328876544,1.0,36083228,0.140925,0.000946,4.550292e-01,0.000690,0,"October 01, 2019 Tuesday, 15:08:40","October 15, 2019 Tuesday, 20:03:18"
2,4d153217-e06d-4581-8924-702c7f757610,2,22,1,3.095637,180.977516,0.935320,0.045982,4,0,...,2175094838038844672,2.0,1002263,0.000294,0.000945,9.102017e-08,0.000690,0,"October 14, 2019 Monday, 21:17:24","October 23, 2019 Wednesday, 21:56:30"
3,e65a6869-fb45-4f34-8482-c80278676d0f,2,2,1,1.089128,4.338280,0.417055,0.028476,0,0,...,2053013568140556288,3.0,1003257,0.150107,0.000945,4.550279e-01,0.000739,0,"October 05, 2019 Saturday, 21:54:13","October 17, 2019 Thursday, 13:54:29"
4,d8206742-06d7-42a2-8163-d70f9dd6cb18,5,1,1,0.329814,3.180891,2.485720,0.094812,5,0,...,2053013558410492160,1.0,13728056,0.267784,0.000945,4.550284e-01,0.000690,0,"October 09, 2019 Wednesday, 13:33:22","October 29, 2019 Tuesday, 11:51:04"
5,3e095d1f-cc89-4c2a-9fe9-346f0878ee72,4,2,1,0.836016,4.297782,0.442338,0.058901,5,0,...,2053013557948264960,1.0,1003156,0.000085,0.000945,1.053642e-02,0.000690,0,"October 04, 2019 Friday, 13:12:56","October 17, 2019 Thursday, 08:19:35"
6,ece2a8db-2d67-4570-bcde-7e732dbd3d93,2,7,1,2.391027,1.200515,0.607836,0.056137,5,0,...,2053013561420136448,16.0,1028809,0.000002,0.000961,3.287986e-02,0.000690,0,"October 10, 2019 Thursday, 22:18:35","October 16, 2019 Wednesday, 20:01:30"
7,e3887764-a39b-4377-b977-2f4e520a4849,10,2,4,11.567454,4.980245,0.020155,0.711252,5,0,...,2053013560570199296,2.0,1004357,0.000006,0.000945,4.550292e-01,0.000689,0,"October 13, 2019 Sunday, 07:59:25","October 13, 2019 Sunday, 04:02:42"
8,8ecc8c53-b0f5-45fb-850a-d92c73ca45d2,3,2,2,1.524405,51.365034,2.617669,0.026307,5,0,...,2060367302192147968,2.0,34062070,0.107357,0.000946,2.449528e-04,0.000737,0,"October 10, 2019 Thursday, 09:52:05","October 31, 2019 Thursday, 11:13:33"
9,4a344f8f-a75c-47d3-a732-7366401493d3,2,2,1,0.315020,14.639583,2.987015,0.003720,5,0,...,2053013563707219968,1.0,28575102,0.267809,0.000945,4.550292e-01,0.000689,0,"October 08, 2019 Tuesday, 00:30:36","October 27, 2019 Sunday, 04:19:38"

In [11]:
# total_duration
out_df['total_duration'] = data_df['total_duration'].apply(lambda x: round(x,2))
out_df.head(10)

,total_duration,is_special_day,prod_views_freqs,prod_buys_freqs,give_big_discount,prod_views_buys_ratio,loyalty_points,total_inventory,time_spec_points
0,166.71,0,0,0,0,0,0,0,0
1,0.43,0,0,0,0,0,0,0,0
2,0.94,0,0,0,0,0,0,0,0
3,0.42,0,0,0,0,0,0,0,0
4,2.49,0,0,0,0,0,0,0,0
5,0.44,0,0,0,0,0,0,0,0
6,0.61,0,0,0,0,0,0,0,0
7,0.02,0,0,0,0,0,0,0,0
8,2.62,0,0,0,0,0,0,0,0
9,2.99,0,0,0,0,0,0,0,0